### PR TITLE
feat(react): add Switch component

### PR DESCRIPTION
**Pull request by pavinduLakshan**
### Purpose

$subject

https://github.com/wso2/oxygen-ui/assets/41533942/d01a7197-b696-4531-9773-f1cf7fd957ec

### Related Issues
- https://github.com/wso2/oxygen-ui/issues/2

### Related PRs
- N/A

### Checklist
- [ ] UX/UI review done on the final implementation.
- [ ] Story provided. (Add screenshots)
- [ ] Manual test round performed and verified.
- [ ] Unit tests provided. (Add links if there are any)
- [ ] Documentation provided. (Add links if there are any)

### Security checks
- [x] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
- [ ] Ran FindSecurityBugs plugin and verified report?
- [x] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

### CODE REVIEW

**Comment by savindi7** [comment]
we need to change the commit messages according to the guidelines https://github.com/wso2/oxygen-ui/blob/main/CONTRIBUTING.md#commit-message-guidelines @pavinduLakshan

**Comment by pavinduLakshan** [comment]
> we need to change the commit messages according to the guidelines https://github.com/wso2/oxygen-ui/blob/main/CONTRIBUTING.md#commit-message-guidelines @pavinduLakshan

Fixed

**Comment by savindi7** [comment]
Screenshot 2023-11-01 at 11 14 31

Not sure why it seems like the switch button isn't aligned to the center.  @pavinduLakshan

**Comment by pavinduLakshan** [comment]
> Screenshot 2023-11-01 at 11 14 31
> Not sure why it seems like the switch button isn't aligned to the center. @pavinduLakshan

Fixed the issue. Thanks 🙌

**Review by savindi7 — APPROVED** [review]

**Pull request merged**
